services:
  voice-banking-frontend-blue:
    container_name: voice-banking-frontend-blue
    image: voice-banking-frontend-blue:deploy
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: ${VITE_API_BASE:-https://voicebanking.joshsoftware.com}
        VITE_AUTH_API_BASE: ${VITE_AUTH_API_BASE:-https://voicebanking.joshsoftware.com}
        VITE_VOICEPRINT_API_BASE: ${VITE_VOICEPRINT_API_BASE:-http://localhost:7860}
        VITE_ADMIN_USERNAME: ${VITE_ADMIN_USERNAME:-admin}
        VITE_ADMIN_PASSWORD: ${VITE_ADMIN_PASSWORD:-VoiceBank@2026}
    ports:
      - "8085:80"
    restart: unless-stopped

  voice-banking-frontend-green:
    container_name: voice-banking-frontend-green
    image: voice-banking-frontend-green:deploy
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: ${VITE_API_BASE:-https://voicebanking.joshsoftware.com}
        VITE_AUTH_API_BASE: ${VITE_AUTH_API_BASE:-https://voicebanking.joshsoftware.com}
        VITE_VOICEPRINT_API_BASE: ${VITE_VOICEPRINT_API_BASE:-http://localhost:7860}
        VITE_ADMIN_USERNAME: ${VITE_ADMIN_USERNAME:-admin}
        VITE_ADMIN_PASSWORD: ${VITE_ADMIN_PASSWORD:-VoiceBank@2026}
    ports:
      - "8086:80"
    restart: unless-stopped