FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi

COPY . .

# Build-time env vars used by Vite (optional overrides at build time)
ARG VITE_API_BASE
ARG VITE_AUTH_API_BASE
ARG VITE_VOICEPRINT_API_BASE
ARG VITE_JAVA_API_BASE
ARG VITE_ADMIN_USERNAME
ARG VITE_ADMIN_PASSWORD
ARG VITE_ENROLLMENT_TOTAL_STEPS
ARG VITE_ENABLE_VOICE_FOLLOWUP
ARG SARVAM_API_KEY
ENV VITE_API_BASE=${VITE_API_BASE}
ENV VITE_AUTH_API_BASE=${VITE_AUTH_API_BASE}
ENV VITE_VOICEPRINT_API_BASE=${VITE_VOICEPRINT_API_BASE}
ENV VITE_JAVA_API_BASE=${VITE_JAVA_API_BASE}
ENV VITE_ADMIN_USERNAME=${VITE_ADMIN_USERNAME}
ENV VITE_ADMIN_PASSWORD=${VITE_ADMIN_PASSWORD}
ENV VITE_ENROLLMENT_TOTAL_STEPS=${VITE_ENROLLMENT_TOTAL_STEPS}
ENV VITE_ENABLE_VOICE_FOLLOWUP=${VITE_ENABLE_VOICE_FOLLOWUP}
ENV SARVAM_API_KEY=${SARVAM_API_KEY}

RUN npm run build

FROM nginx:1.27-alpine AS runner

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]